export enum NotificationType {
    COMMENT ='COMMENT',
    PAYMENT = 'PAYMENT',
    PROMOTION='PROMOTION',
    SYSTEM_ALERT='SYSTEM_ALERT',
    CERTIFICATION='CERTIFICATION',
    REMINDER='REMINDER',
}
